version: '3'

services:
  neo4j:
    build:
      context: ./src/
      dockerfile: neo4j.Dockerfile
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./storage/neo4j/data:/data
      - ./storage/neo4j/logs:/logs

  api:
    build:
      context: ./src/
      dockerfile: api.Dockerfile
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    environment:
      PYTHONDONTWRITEBYTECODE : 1
      PYTHONUNBUFFERED : 1
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/
      - ./src/api/run.sh:/usr/src/app/api/run.sh

  worker:
    build:
      context: ./src/
      dockerfile: worker.Dockerfile
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE : 1
      PYTHONUNBUFFERED : 1
    container_name: worker
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/
      - ./src/worker/run.sh:/usr/src/app/worker/run.sh