version: '3'

services:
  db:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    env_file:
      - .env.database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    # restart: on-failure:5 # attempt to restart 5 times if the container fails
    restart: always
    depends_on:
      - db
        # condition: service_healthy # only start the api container once the db container is healthy
    ports:
      - "8080:8080"
    env_file:
      - .env.api
    volumes:
      - ./api:/Moment-Server/api
      - ./db/data:/Moment-Server/data
    # command: sh -c "sleep 5"