version: '3.4'

services:
  api:
    build:
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    # Maybe add volumes?
  worker:
    build:
      context: ./
      dockerfile: worker.Dockerfile
    env_file:
      - .env
    # Maybe add volumes?
  s3-emulator:
    command: server /s3/data --console-address ":9001"
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - moment-s3:moment-s3/s3/data
    environment:
      MINIO_ROOT_USER : ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD : ${MINIO_ROOT_PASSWORD:-mkcadmin123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  neo4j:
    image: neo4j:latest
    container_name: moment-db
    restart: always
    env_file:
      - .env.database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./moment-db:/data
      - ./moment-db:/logs

      
volumes:
  moment-db:
  moment-s3: