version: '3.4'

services:
  db:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./common/db/storage/data:/data
      - ./common/db/storage/logs:/logs

  s3-emulator:
    container_name: s3
    command: server /s3/data --console-address ":9001"
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - mkc-s3:/s3/data
    environment:
      MINIO_ROOT_USER : ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD : ${MINIO_ROOT_PASSWORD:-mkcadmin123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      PYTHONDONTWRITEBYTECODE : 1
      PYTHONUNBUFFERED : 1
    volumes:
      - ./common/db/s3/storage/data:/data

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./api:/Moment-Server/api
      - ./db/data:/Moment-Server/data
    # command: sh -c "sleep 5"