version: '3'

services:
  db:
    build:
      context: .
      dockerfile: neo4j.Dockerfile
    container_name: neo4j
    restart: always
    env_file:
      - .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./storage/db/data:/data
      - ./storage/db/logs:/logs

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    # restart: on-failure:5 # attempt to restart 5 times if the container fails
    restart: always
    depends_on:
      - db
        # condition: service_healthy # only start the api container once the db container is healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./api:/api
      - ./common:/common
    # command: sh -c "sleep 5"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    restart: always
    container_name: worker
    env_file:
      - .env
    volumes:
      - .:/app
      - ./worker:/worker
      - ./common:/common